language: node_js
node_js:
  - "4"
  - "5"

before_script:
  - npm prune

script:
  - npm test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/codecov

cache:
  directories:
    - node_modules
